server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wms?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456


# 日期转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#  Redis配置信息
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password: null

mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.eshore.wms.pojo
